alias rc='bundle exec rails console'
alias rd='bundle exec rails destroy'
alias rdb='bundle exec rails dbconsole'
alias rdbm='bundle exec rake db:migrate db:test:clone'
alias rg='bundle exec rails generate'
alias rgm='bundle exec rails generate migration'
alias rp='bundle exec rails plugin'
alias ru='bundle exec rails runner'
# alias rs='bundle exec rails server'
alias rs='bundle exec rails server -b 127.0.0.1 -p 3000 -d -e development'
alias rsk='cat tmp/pids/server.pid | xargs kill'
# alias rsd='bundle exec rails server --debugger'
alias devlog='tail -f log/development.log'
alias rdm='bundle exec rake db:migrate'
alias rdr='bundle exec rake db:rollback'
alias migrate='bundle exec rake db:migrate db:test:clone'
# alias r='rails'
alias rcs='bundle exec rails console --sandbox'

# needed lest zsh swallow rake task args
alias rake='noglob rake'
