# $HOME/Gemfile - jeff@jrhorn.me
#
# A gemfile for all those system utilities you want outside your projects
#

source "https://rubygems.org"

gem 'github-auth'
gem 'git-pairing'
gem 'bundler'
gem 'gem-ctags'
gem 'gem-release'
gem 'gem-browse'
gem 'yard'
gem 'hookup'
gem 'pry'
gem 'pry-clipboard'
gem 'pry-nav'
gem 'discover-unused-partials'
gem 'hub'
gem 'gx'
gem 'infect'
gem 'lunchy'
gem 'tmuxinator'
gem 'interactive_editor'
gem 'awesome_print'
gem 'irbtools'
gem 'irbtools-more'
gem 'wirb'
gem 'wirble'
gem 'hirb'
gem 'hirb-unicode'
gem 'pry-theme'
gem 'desktop'
